version: '3.8'

services:
  postgres:
    container_name: container_db_gestao_vagas
    image: postgres
    ports:
      - 5480:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_gestao_vagas
